name: idash
description: "A dashboard for your mental health."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_ui_auth: ^1.15.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  cloud_firestore: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.2
  integration_test:
    sdk: flutter
  fake_cloud_firestore: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/heart.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/heart.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/heart.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/heart.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/heart.png"