// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtWL00VMbBWVfdsM3ZVFh4m4VCqv6ik4',
    appId: '1:386849417277:web:5e2d7e34cf7c665be7e254',
    messagingSenderId: '386849417277',
    projectId: 'idash-13ef7',
    authDomain: 'idash-13ef7.firebaseapp.com',
    storageBucket: 'idash-13ef7.appspot.com',
    measurementId: 'G-VRJZ19FDT1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDesfIisQ2Cjj6irRAtm8mUe7FRu-ZnfvE',
    appId: '1:386849417277:ios:0182cc8affb1fd65e7e254',
    messagingSenderId: '386849417277',
    projectId: 'idash-13ef7',
    storageBucket: 'idash-13ef7.appspot.com',
    iosClientId: '386849417277-32bq82vi034sd3h1sqejvnlaokkaagf5.apps.googleusercontent.com',
    iosBundleId: 'com.mgbvox.idash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDesfIisQ2Cjj6irRAtm8mUe7FRu-ZnfvE',
    appId: '1:386849417277:ios:0182cc8affb1fd65e7e254',
    messagingSenderId: '386849417277',
    projectId: 'idash-13ef7',
    storageBucket: 'idash-13ef7.appspot.com',
    iosClientId: '386849417277-32bq82vi034sd3h1sqejvnlaokkaagf5.apps.googleusercontent.com',
    iosBundleId: 'com.mgbvox.idash',
  );
}
