// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZncN0oN4gxqLz0sasPIIio0xMR-PhxIw',
    appId: '1:718962825258:web:dde09725132ae634234b53',
    messagingSenderId: '718962825258',
    projectId: 'auth-demo-672c9',
    authDomain: 'auth-demo-672c9.firebaseapp.com',
    storageBucket: 'auth-demo-672c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCToBMYQGJ0QY6pavvYMYk3d2c-pLypuh4',
    appId: '1:718962825258:android:3202b458204268a2234b53',
    messagingSenderId: '718962825258',
    projectId: 'auth-demo-672c9',
    storageBucket: 'auth-demo-672c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Sc2Ew7lu_b2fpt617OkumPXyi4fGEps',
    appId: '1:718962825258:ios:f3261628874d8c3b234b53',
    messagingSenderId: '718962825258',
    projectId: 'auth-demo-672c9',
    storageBucket: 'auth-demo-672c9.appspot.com',
    iosClientId: '718962825258-l05ji26518shue5n46a36338sihre955.apps.googleusercontent.com',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Sc2Ew7lu_b2fpt617OkumPXyi4fGEps',
    appId: '1:718962825258:ios:f3261628874d8c3b234b53',
    messagingSenderId: '718962825258',
    projectId: 'auth-demo-672c9',
    storageBucket: 'auth-demo-672c9.appspot.com',
    iosClientId: '718962825258-l05ji26518shue5n46a36338sihre955.apps.googleusercontent.com',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZncN0oN4gxqLz0sasPIIio0xMR-PhxIw',
    appId: '1:718962825258:web:b81a24508d3d6182234b53',
    messagingSenderId: '718962825258',
    projectId: 'auth-demo-672c9',
    authDomain: 'auth-demo-672c9.firebaseapp.com',
    storageBucket: 'auth-demo-672c9.appspot.com',
  );
}